name: 'Update changelog version'
description: 'Use calendar versioning to organise your changelog'
inputs:
  token:
    description: 'GitHub token'
    required: true
  filePath:
    description: 'Path to your changelog'
  prefix:
    description: 'What commits need to start with to be included in the changelog output'
outputs:
  newTag:
    description: 'New tag for the release'
  changelog:
    description: 'The changes for the newest release'
runs:
  using: 'node20'
  main: 'dist/index.js'
